//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_TO_POEDI_TRAIN
    {
        public string pr_no { get; set; }
        public string pr_line { get; set; }
        public string isTransfer { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string PIC { get; set; }
        public string vendor { get; set; }
        public string item { get; set; }
        public string description { get; set; }
        public double QTY { get; set; }
        public string unitPack { get; set; }
        public System.DateTime duedate { get; set; }
        public string investmentNo { get; set; }
        public string investmentName { get; set; }
        public string accountCode { get; set; }
        public string costCode { get; set; }
        public string costCodeNote { get; set; }
        public double unitPrice { get; set; }
        public string brand { get; set; }
        public string quotation { get; set; }
        public System.DateTime ApprovedDate { get; set; }
        public System.TimeSpan ApprovedTime { get; set; }
        public string IssueBy { get; set; }
        public string IssueGroup { get; set; }
        public string CostNote { get; set; }
        public string Model { get; set; }
        public string WONo { get; set; }
        public string Purpose { get; set; }
        public string vQuoNo { get; set; }
        public string Sparepart { get; set; }
        public string MTC { get; set; }
        public string PRUser { get; set; }
        public string ProjectName { get; set; }
        public string Reason { get; set; }
    }
}
