//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_eta_tnc
    {
        public string pr_no { get; set; }
        public short pr_line { get; set; }
        public string invoice_no { get; set; }
        public int rec_qty { get; set; }
        public System.DateTime eta_tnc { get; set; }
        public string file_path { get; set; }
    
        public virtual td_tooling td_tooling { get; set; }
    }
}
