//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_files
    {
        public string pr_no { get; set; }
        public string file_name { get; set; }
        public byte file_type { get; set; }
        public string file_path { get; set; }
        public System.DateTime upl_dt { get; set; }
        public string upl_by { get; set; }
    
        public virtual td_pr td_pr { get; set; }
        public virtual tm_file_type tm_file_type { get; set; }
    }
}
