//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_import
    {
        public string delivery_status { get; set; }
        public string po_no { get; set; }
        public string po_added { get; set; }
        public string plant { get; set; }
        public string product { get; set; }
        public string order_name { get; set; }
        public string spec { get; set; }
        public string order_status { get; set; }
        public Nullable<int> order_qty { get; set; }
        public Nullable<int> insp_qty { get; set; }
        public Nullable<int> ship_qty { get; set; }
        public string destination { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<bool> del_flag { get; set; }
    }
}
