//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_pr
    {
        public td_pr()
        {
            this.td_files = new HashSet<td_files>();
            this.td_tooling = new HashSet<td_tooling>();
            this.td_tran = new HashSet<td_tran>();
        }
    
        public string pr_no { get; set; }
        public string condition { get; set; }
        public System.DateTime due_date { get; set; }
        public string reason { get; set; }
        public System.DateTime issue_dt { get; set; }
        public string issue_by { get; set; }
        public int issue_group { get; set; }
        public Nullable<int> issue_dept { get; set; }
        public Nullable<int> issue_plant { get; set; }
        public string ext { get; set; }
        public string rank { get; set; }
        public string cost_code { get; set; }
        public string item_code { get; set; }
        public string problem { get; set; }
        public byte process { get; set; }
        public byte nok_plant { get; set; }
        public byte product { get; set; }
        public byte type { get; set; }
        public string nok_contact { get; set; }
        public string issue_name { get; set; }
        public string po_no { get; set; }
        public string issue_group_name { get; set; }
        public string po_nok { get; set; }
        public string order_no { get; set; }
        public string plant { get; set; }
        public string maker { get; set; }
        public Nullable<System.DateTime> maker_comp_dt { get; set; }
        public Nullable<System.DateTime> div_comp_dt { get; set; }
        public Nullable<byte> site_id { get; set; }
    
        public virtual ICollection<td_files> td_files { get; set; }
        public virtual tm_nok_plant tm_nok_plant { get; set; }
        public virtual tm_process tm_process { get; set; }
        public virtual tm_product tm_product { get; set; }
        public virtual tm_type tm_type { get; set; }
        public virtual ICollection<td_tooling> td_tooling { get; set; }
        public virtual ICollection<td_tran> td_tran { get; set; }
        public virtual tm_site tm_site { get; set; }
    }
}
