//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_file_type
    {
        public tm_file_type()
        {
            this.td_files = new HashSet<td_files>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<td_files> td_files { get; set; }
    }
}
