//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_leadtime
    {
        public byte process { get; set; }
        public byte plant { get; set; }
        public byte product { get; set; }
        public byte type { get; set; }
        public int etd { get; set; }
        public int inspection { get; set; }
        public int making { get; set; }
        public int trial { get; set; }
        public int shipping { get; set; }
        public int eta { get; set; }
    
        public virtual tm_nok_plant tm_nok_plant { get; set; }
        public virtual tm_process tm_process { get; set; }
        public virtual tm_product tm_product { get; set; }
        public virtual tm_type tm_type { get; set; }
    }
}
