//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_status
    {
        public tm_status()
        {
            this.td_tran = new HashSet<td_tran>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
        public Nullable<byte> lv_min { get; set; }
        public Nullable<byte> lv_max { get; set; }
        public Nullable<byte> next { get; set; }
        public string name2 { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<td_tran> td_tran { get; set; }
    }
}
