//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_user_lv
    {
        public tm_user_lv()
        {
            this.td_tran = new HashSet<td_tran>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
        public Nullable<byte> min { get; set; }
        public Nullable<byte> max { get; set; }
    
        public virtual ICollection<td_tran> td_tran { get; set; }
    }
}
