//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_user_type
    {
        public tm_user_type()
        {
            this.tm_user = new HashSet<tm_user>();
        }
    
        public byte id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<tm_user> tm_user { get; set; }
    }
}
