//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tnc_user_level
    {
        public byte ulv_id { get; set; }
        public string ulv_detail { get; set; }
        public Nullable<byte> position_min { get; set; }
        public Nullable<byte> position_max { get; set; }
    }
}
