//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sys_user
    {
        public string emp_code { get; set; }
        public byte utype_id { get; set; }
        public string name { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string email { get; set; }
        public string emp_status { get; set; }
    }
}
