//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tran_show
    {
        public string pr_no { get; set; }
        public string status { get; set; }
        public string lv { get; set; }
        public string action { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public System.DateTime act_dt { get; set; }
        public string comment { get; set; }
        public byte ulv_id { get; set; }
        public int org { get; set; }
        public byte status_id { get; set; }
        public string act_id { get; set; }
        public byte rev { get; set; }
    }
}
