//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TncNokTooling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tran
    {
        public string pr_no { get; set; }
        public string item_code { get; set; }
        public string condition { get; set; }
        public System.DateTime due_date { get; set; }
        public string rank { get; set; }
        public System.DateTime issue_dt { get; set; }
        public System.DateTime act_dt { get; set; }
        public string group_name { get; set; }
        public int issue_group { get; set; }
        public string po_no { get; set; }
        public string status { get; set; }
        public byte status_id { get; set; }
        public byte ulv_id { get; set; }
        public byte process { get; set; }
        public byte nok_plant { get; set; }
        public int org { get; set; }
        public string requester { get; set; }
        public string site_name { get; set; }
    }
}
