//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPOFixed
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_APP_TRANSACTION
    {
        public string CompanyCode { get; set; }
        public string PONO { get; set; }
        public int AppCount { get; set; }
        public byte AppLevel { get; set; }
        public string AppUser { get; set; }
        public Nullable<bool> AppAction { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
    
        public virtual PO_APP_HEAD PO_APP_HEAD { get; set; }
    }
}
