//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPOFixed
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_APP_LINE
    {
        public string RecordStatus { get; set; }
        public string CompanyCode { get; set; }
        public string PONO { get; set; }
        public string POLine { get; set; }
        public int AppCount { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.TimeSpan> EntryTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.TimeSpan> UpdateTime { get; set; }
        public string AppSign { get; set; }
        public string AppMemo { get; set; }
        public string AppReqSign { get; set; }
        public string AppReqReceipt { get; set; }
        public string AppRepSign { get; set; }
        public string AppRepReceipt { get; set; }
        public string Item { get; set; }
        public Nullable<double> PurchaseQTY { get; set; }
        public string UnitPack { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> IncomingDay { get; set; }
        public Nullable<System.DateTime> IncomingDate { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public string CostCenterCode { get; set; }
        public string MTCode { get; set; }
        public string InvestmentNo { get; set; }
        public string AccountCode { get; set; }
        public string PRNO { get; set; }
        public Nullable<int> Quotation { get; set; }
        public string BuyerMemo { get; set; }
        public string POStatus { get; set; }
    
        public virtual PO_APP_HEAD PO_APP_HEAD { get; set; }
    }
}
