//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPOFixed
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PREntities : DbContext
    {
        public PREntities()
            : base("name=PREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PO_APP_HEAD> PO_APP_HEAD { get; set; }
        public DbSet<PO_APP_LINE> PO_APP_LINE { get; set; }
        public DbSet<PO_APP_TRANSACTION> PO_APP_TRANSACTION { get; set; }
    }
}
