//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPOFixed
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_tran
    {
        public string pr_no { get; set; }
        public byte status_id { get; set; }
        public byte ulv_id { get; set; }
        public int org { get; set; }
        public byte rev { get; set; }
        public string actor { get; set; }
        public string act_id { get; set; }
        public System.DateTime act_dt { get; set; }
        public string comment { get; set; }
    
        public virtual td_pr td_pr { get; set; }
    }
}
