//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetPOFixed
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_user_nok
    {
        public string username { get; set; }
        public string password { get; set; }
        public byte utype { get; set; }
        public string email { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<byte> ulv { get; set; }
        public string vcode { get; set; }
        public bool active { get; set; }
    }
}
